### ISSUE TITLE
windows client stays in logging in  status 

### ISSUE THREAD

**Issue by no-trace-of-time** [omniedgeio/omniedge#11]
systray status:
![1](https://user-images.githubusercontent.com/820618/181211692-4aed6acc-b02a-4d2f-81fb-061166ced91b.gif)

in dashboard https://omniedge.io/dashboard/virtual-networks/vnw_xxxxx ....
I can only see other device, no this windows notebook device.

thanks

**Comment by yongqianme** [comment]
You can not see the windows devices in the dashboard because it is not registered yet. The sequence is first login, then join a virtual network, after you can see the device in the dashboard. 

Regarding your login problem ? 

1. What is your windows version ? 
2. What is your OmniEdge Windows version ? 

Would you try quit and open again ?

**Comment by no-trace-of-time** [comment]
My enviroment: windows 10 upgrade to latest version, ominiedge 0.2.3

I get more test results:
1. I must  join one specific network via systray to see my notebook device under this network.
2. After I logout and remove this notebook device from network, I can still ping it's 100.100.0.3 ip address
Windows ipconfig /all output:
以太网适配器 以太网 2:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : TAP-Windows Adapter V9
   物理地址. . . . . . . . . . . . . : 00-FF-25-DA-5E-B5
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是

PS C:\Users\SimonXu> ping 100.100.0.3

正在 Ping 100.100.0.3 具有 32 字节的数据:
来自 100.100.0.3 的回复: 字节=32 时间<1ms TTL=128
来自 100.100.0.3 的回复: 字节=32 时间<1ms TTL=128
来自 100.100.0.3 的回复: 字节=32 时间<1ms TTL=128
来自 100.100.0.3 的回复: 字节=32 时间<1ms TTL=128

100.100.0.3 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 0ms，最长 = 0ms，平均 = 0ms

3.Redo login , join process, notebook ip address changes from 0.3 to 0.1
ping from notebook to smartphone is ok.


4. Detach notebook from network and disconnect. 
以太网适配器 以太网 2:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : TAP-Windows Adapter V9
   物理地址. . . . . . . . . . . . . : 00-FF-25-DA-5E-B5
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . : home
   描述. . . . . . . . . . . . . . . : Intel(R) Centrino(R) Wireless-N 1000
   物理地址. . . . . . . . . . . . . : 8C-A9-82-B7-4C-02
PS C:\Users\SimonXu> ping 100.100.0.1

正在 Ping 100.100.0.1 具有 32 字节的数据:
来自 100.100.0.1 的回复: 字节=32 时间<1ms TTL=128

100.100.0.1 的 Ping 统计信息:
    数据包: 已发送 = 1，已接收 = 1，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 0ms，最长 = 0ms，平均 = 0ms


I think the disconnect process and result is something strange I don't know.

Thanks.

**Comment by yongqianme** [comment]
Thanks for reply. 

1. Yes. You have to join a virtual network, **join** means connect to the virtual network. Any new devices are listed only when there are joining one virtual network. 
2. Removing your devices doesn't mean you disconnect from your devices. You have to disconnect from your clients. 
3. Remove the device and rejoin again will allocate a new IP address. 

Until now, I think everything is working so far. 

We understand the UX is a little confused, we have a plan to make it more clear.

**Comment by no-trace-of-time** [comment]
How to disconnect from my clients?

**Comment by yongqianme** [comment]
There is a disconnect you can find in the systray.

<img width="398" alt="image" src="https://user-images.githubusercontent.com/93888/181417699-95f9d84c-0d32-47f6-93d9-5094427941b2.png">

**Comment by no-trace-of-time** [comment]
After I disconnected device ( see my screen capture img) , windows network device has no ip address 100.100.0.1 binded, but I can still ping it successfully.

以太网适配器 以太网 2:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :

无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . : home
   本地链接 IPv6 地址. . . . . . . . : fe80::4c6e:81e8:2fa4:d16f%9
   IPv4 地址 . . . . . . . . . . . . : 192.168.10.21
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 192.168.10.8
PS C:\Users\SimonXu> ping 100.100.0.1

正在 Ping 100.100.0.1 具有 32 字节的数据:
来自 100.100.0.1 的回复: 字节=32 时间<1ms TTL=128
来自 100.100.0.1 的回复: 字节=32 时间<1ms TTL=128

100.100.0.1 的 Ping 统计信息:
    数据包: 已发送 = 2，已接收 = 2，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 0ms，最长 = 0ms，平均 = 0ms

![20220728-1](https://user-images.githubusercontent.com/820618/181468813-eac70562-f7b5-4b5e-a0f0-5c2aa3bd6db6.gif)


This is why I think something is wired.

Thanks.

**Comment by yongqianme** [comment]
Would you check with **ipconfig /all **? 
it looks the tap driver with vpn didn't disconnect .

**Comment by no-trace-of-time** [comment]
Retry:
1. Dis-join my network, get ipconfig /all result:
以太网适配器 以太网 2:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : TAP-Windows Adapter V9
   物理地址. . . . . . . . . . . . . : 00-FF-25-DA-5E-B5
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是

There is no 100.100.0.1 ip address bind to this interface.

2. ping 100.100.0.1
PS C:\Users\SimonXu> ping 100.100.0.1

正在 Ping 100.100.0.1 具有 32 字节的数据:
来自 100.100.0.1 的回复: 字节=32 时间<1ms TTL=128
来自 100.100.0.1 的回复: 字节=32 时间<1ms TTL=128
来自 100.100.0.1 的回复: 字节=32 时间<1ms TTL=128

100.100.0.1 的 Ping 统计信息:
    数据包: 已发送 = 3，已接收 = 3，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 0ms，最长 = 0ms，平均 = 0ms


This ip can still be pinged.

3. Dashboard output:
simonxu-lenovo-e47g
	windows 10	

My Omni Network
100.100.0.1

This device still stay in Device list with its ip address.

4. Systray status: Offline

What is wired: no network interface has 100.100.0.1 binded, but I can still ping this address.

Thanks.

**Comment by no-trace-of-time** [comment]
ipconfig /all output detail:

Windows IP 配置

   主机名  . . . . . . . . . . . . . : simonxu-lenovo-e47g
   主 DNS 后缀 . . . . . . . . . . . : 
   节点类型  . . . . . . . . . . . . : 混合
   IP 路由已启用 . . . . . . . . . . : 否
   WINS 代理已启用 . . . . . . . . . : 否
   DNS 后缀搜索列表  . . . . . . . . : home

以太网适配器 以太网:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : home
   描述. . . . . . . . . . . . . . . : Intel(R) 82579V Gigabit Network Connection
   物理地址. . . . . . . . . . . . . : E8-9A-8F-7A-96-A3
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

以太网适配器 以太网 2:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : TAP-Windows Adapter V9
   物理地址. . . . . . . . . . . . . : 00-FF-25-DA-5E-B5
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . : home
   描述. . . . . . . . . . . . . . . : Intel(R) Centrino(R) Wireless-N 1000
   物理地址. . . . . . . . . . . . . : 8C-A9-82-B7-4C-02
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::4c6e:81e8:2fa4:d16f%9(首选) 
   IPv4 地址 . . . . . . . . . . . . : 192.168.10.21(首选) 
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2022年7月29日 8:40:49
   租约过期的时间  . . . . . . . . . : 2022年7月29日 10:10:49
   默认网关. . . . . . . . . . . . . : 192.168.10.8
   DHCP 服务器 . . . . . . . . . . . : 192.168.10.8
   DHCPv6 IAID . . . . . . . . . . . : 93104514
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-29-05-7B-76-E8-9A-8F-7A-96-A3
   DNS 服务器  . . . . . . . . . . . : 192.168.10.8
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用


Thanks

**Comment by yongqianme** [comment]
Just tried on my windows PC, windows 10, OmniEdge version 0.2.3, there is no problem here. 
Do you have any devices ? Or Would you try by deleting the virtual network and creating a new one with different IP range ? 

```
C:\Users\Admin>ipconfig

Windows IP Configuration

Ethernet adapter 5:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::4d12:fe9c:8f99:ccf6%23
   IPv4 Address. . . . . . . . . . . : 100.100.100.48
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

C:\Users\Admin>ping 100.100.100.51

Pinging 100.100.100.51 with 32 bytes of data:
Reply from 100.100.100.51: bytes=32 time=38ms TTL=64
Reply from 100.100.100.51: bytes=32 time=19ms TTL=64
Reply from 100.100.100.51: bytes=32 time=19ms TTL=64
Reply from 100.100.100.51: bytes=32 time=19ms TTL=64

Ping statistics for 100.100.100.51:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 19ms, Maximum = 38ms, Average = 23ms

C:\Users\Admin>ipconfig

Windows IP Configuration

Ethernet adapter  5:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

C:\Users\Admin>ping 100.100.100.51

Pinging 100.100.100.51 with 32 bytes of data:
Request timed out.
Request timed out.

Ping statistics for 100.100.100.51:
    Packets: Sent = 2, Received = 0, Lost = 2 (100% loss),
Control-C
^C
C:\Users\Admin>
```

**Comment by yongqianme** [comment]
Would you send a screenshot of your virtual network setting ? Like the following pic

<img width="649" alt="image" src="https://user-images.githubusercontent.com/93888/181667936-bbb39280-8cd5-4366-8233-e14fb6a1d423.png">

**Comment by no-trace-of-time** [comment]
dashboard screenshot

![image](https://user-images.githubusercontent.com/820618/181729391-2555ab7b-80ac-4a5b-8823-8a7aaefa4679.png)

**Comment by no-trace-of-time** [comment]
I have no other device on the notebook.
I thinks LAN 2 interface is created by omniedge for tap driver.
Test1:   I start zerotier-one, there is a new virtual network interface device created. When I disconnect from zerotier-one, the newly added network interface disappered.

Test2: I temp disable LAN2 interface. Then when I join omniedge via systray, its icon disappers just like the application quit abnormally.  Then I re-enable LAN2 interface, the omniedge systray icon function normally as before.

I just find no way to delete this LAN2 interface.

**Comment by no-trace-of-time** [comment]
I will try device manager to delete that interface.

**Comment by no-trace-of-time** [comment]
Uninstall TAP device in device manager, which get the same result in TEST2.

sad :-(

**Comment by no-trace-of-time** [comment]
Retest zerotier-one, connect functions ok.

**Comment by no-trace-of-time** [comment]
Reboot notebook, the same result for omniedge & zerotier-one

**Comment by yongqianme** [comment]
I am afraid there is some conflict between omniedge and zerotier, because both of them are using tap drivers.

**Comment by no-trace-of-time** [comment]
But I have uninstalled TAP network driver, zerotier-one functions ok.

Wired...

Thanks.

Later I can uninstall zerotier and test omniedge alone.

**Comment by no-trace-of-time** [comment]
Further test:
1. uninstall zerotier-one
2. reboot
3. uninstal omniedge
4. reinstall omniedge, which also reinstall TAP network driver
5. after reinstall omniedge, ipconfig /all shows TAP-network interface recreated
以太网适配器 以太网 2:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : TAP-Windows Adapter V9
   物理地址. . . . . . . . . . . . . : 00-FF-8C-D7-0D-1B
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是

6. connect omniedge, ping local ip: 100.100.0.4 ,ok
7. disconnect omniedge, ipconfig /all|more, the ip binded to tap-interface disappeared.
8. ping previous 100.100.0.4 ip , still can be pinged.
C:\Users\SimonXu>ping 100.100.0.4

正在 Ping 100.100.0.4 具有 32 字节的数据:
来自 100.100.0.4 的回复: 字节=32 时间<1ms TTL=128
来自 100.100.0.4 的回复: 字节=32 时间<1ms TTL=128

100.100.0.4 的 Ping 统计信息:
    数据包: 已发送 = 2，已接收 = 2，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 0ms，最长 = 0ms，平均 = 0ms


==================
ipconfig /all output:

Windows IP 配置

   主机名  . . . . . . . . . . . . . : simonxu-lenovo-e47g
   主 DNS 后缀 . . . . . . . . . . . : 
   节点类型  . . . . . . . . . . . . : 混合
   IP 路由已启用 . . . . . . . . . . : 否
   WINS 代理已启用 . . . . . . . . . : 否
   DNS 后缀搜索列表  . . . . . . . . : home

以太网适配器 以太网:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : home
   描述. . . . . . . . . . . . . . . : Intel(R) 82579V Gigabit Network Connection
   物理地址. . . . . . . . . . . . . : E8-9A-8F-7A-96-A3
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是

以太网适配器 以太网 2:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : 
   描述. . . . . . . . . . . . . . . : TAP-Windows Adapter V9
   物理地址. . . . . . . . . . . . . : 00-FF-8C-D7-0D-1B
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是

无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . : home
   描述. . . . . . . . . . . . . . . : Intel(R) Centrino(R) Wireless-N 1000
   物理地址. . . . . . . . . . . . . : 8C-A9-82-B7-4C-02
   DHCP 已启用 . . . . . . . . . . . : 是
   自动配置已启用. . . . . . . . . . : 是
   本地链接 IPv6 地址. . . . . . . . : fe80::4c6e:81e8:2fa4:d16f%7(首选) 
   IPv4 地址 . . . . . . . . . . . . : 192.168.10.21(首选) 
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   获得租约的时间  . . . . . . . . . : 2022年8月1日 11:44:39
   租约过期的时间  . . . . . . . . . : 2022年8月1日 12:44:39
   默认网关. . . . . . . . . . . . . : 192.168.10.8
   DHCP 服务器 . . . . . . . . . . . : 192.168.10.8
   DHCPv6 IAID . . . . . . . . . . . : 93104514
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-29-05-7B-76-E8-9A-8F-7A-96-A3
   DNS 服务器  . . . . . . . . . . . : 192.168.10.8
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用


----------------
dashboard device list ( after I disconnected) :
![image](https://user-images.githubusercontent.com/820618/182069457-c6b1dba1-1381-441d-95c6-fd32b04c4300.png)


---- 
dashboard device setting page: 
![image](https://user-images.githubusercontent.com/820618/182069504-7bd0f187-e845-4eb4-b447-c440cd53ade7.png)

**Comment by no-trace-of-time** [comment]
So I think this is nothing to do with zerotier-one

**Comment by yongqianme** [comment]
Just noticed that `100.100.0.4 ` is your own IP of the device, would you try ping `100.100.0.6` when clicking disconnect ?

**Comment by no-trace-of-time** [comment]
PS C:\Users\SimonXu> ipconfig

Windows IP 配置


以太网适配器 以太网:

   媒体状态  . . . . . . . . . . . . : 媒体已断开连接
   连接特定的 DNS 后缀 . . . . . . . : home

以太网适配器 以太网 2:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::e075:d660:58d4:6364%30
   IPv4 地址 . . . . . . . . . . . . : 100.100.0.4
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . :

以太网适配器 ZeroTier One [8286ac0e47ec4e7d]:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::e919:dfe:b9a5:fbe6%34
   IPv4 地址 . . . . . . . . . . . . : 10.147.18.88
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 25.255.255.254

无线局域网适配器 WLAN:

   连接特定的 DNS 后缀 . . . . . . . : home
   本地链接 IPv6 地址. . . . . . . . : fe80::4c6e:81e8:2fa4:d16f%7
   IPv4 地址 . . . . . . . . . . . . : 192.168.10.21
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 192.168.10.8


100.100.0.4 is my own omniedge ip address.

**Comment by yongqianme** [comment]
ping 自己的ip，只要这个ip在的，就一定能ping通的

**Comment by no-trace-of-time** [comment]
我的意思，disconnect之后，TAP LAN2这个接口上没绑定任何ip地址了，竟然能够ping通，这个情况比较奇怪。
connect成功之后，ping通自己这个ip地址，当然是肯定通的。

**Comment by no-trace-of-time** [comment]
相当于ping通了一个ipconfig发现不了的本地地址

**Comment by yongqianme** [comment]
试试断开后其他机器是不是可以ping通这个地址（打开windows的ICMP设置：https://omniedge.io/docs/article/Others#why-cant-ping-my-windows-pc）？ping不通就是真的断了。

**Comment by yongqianme** [comment]
能ping通的原因是因为IP已经设置了还在的，但是连接断开了。如果网卡设置了手动的IP，但是网卡没有插网线，这个ping本地ping也是能ping通的。

<img width="428" alt="image" src="https://user-images.githubusercontent.com/93888/182113101-3fa5d75b-3f64-4d64-93d2-c0b3470f26ec.png">
