### ISSUE TITLE
I can't delete Device 

### ISSUE THREAD

**Issue by cnmeeia** [omniedgeio/omniedge#19]
![](https://raw.githubusercontent.com/cnmeeia/images/main/omniedge/del.png)

**Comment by yongqianme** [comment]
You have to delete it one by one by clicking the action ...

**Comment by yongqianme** [comment]
It looks you created those devices by run a docker or something .

**Comment by cnmeeia** [comment]
How to delete it? I deleted it and it was restored automatically? I don't know which server is running omniedge's docker thank you! ! ! ! !

**Comment by yongqianme** [comment]
It looks there more than 10 devices registered. Did you play it somewhere ? Docker ? GitHub action. You have to stop it anyhow.

**Comment by yongqianme** [comment]
Please send us your omniedge account to support@omniedge.io, let’s help you to take a look.

**Comment by cnmeeia** [comment]
I emailed you. Thanks.

**Comment by yongqianme** [comment]
What is your email address you used to sent the email ?

**Comment by cnmeeia** [comment]
ad.china0731+omniedgeyear@gmail.com
