### ISSUE TITLE
omniedge-v0.2.4-arm64v8.zip  asset not found when install

### ISSUE THREAD

**Issue by kevinpan45** [omniedgeio/omniedge#53]
curl https://omniedge.io/install/omniedge-install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3458  100  3458    0     0   4136      0 --:--:-- --:--:-- --:--:--  4131
[INFO]  Downloading binary zip https://github.com/omniedgeio/omniedge/releases/download/v0.2.4/omniedge-v0.2.4-arm64v8.zip

wget https://github.com/omniedgeio/omniedge/releases/download/v0.2.4/omniedge-v0.2.4-arm64v8.zip
--2022-10-25 14:56:50--  https://github.com/omniedgeio/omniedge/releases/download/v0.2.4/omniedge-v0.2.4-arm64v8.zip
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-10-25 14:56:51 ERROR 404: Not Found.

**Comment by yongqianme** [comment]
Thanks, the bug is fixed in the latest script, the SUFFIX is arm64v8 but the package is arm64. 

```
 arm64)
        ARCH=arm64
        SUFFIX=arm64
        ;;
    aarch64)
        ARCH=arm64
        SUFFIX=arm64
        ;;
```
